name: Deploy to Azure Web App - megazone

on:
  push:
    branches:
      - agentic-ai-copilot
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'megazone'
          slot-name: 'agentic-ai-copilot'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_15BE65AF706948CD902172D07611766A }}
          package: .
